spring:
  datasource:
    url: jdbc:mysql://localhost/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: 123456
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
    bus:
      enabled: true
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
security:
  basic:
    enabled: false
  ignored: /swagger-ui.html,/swagger-resources/**, /webjars/** , /docs/**
choerodon:
  eureka:
    event:
      max-cache-size: 300
      retry-time: 5
      retry-interval: 3
      skip-services: config**, **register-server, **gateway**, zipkin**, hystrix**, oauth**
  swagger:
    client: client
    oauth-url: http://localhost:8080/oauth/oauth/authorize
  gateway:
    domain: 127.0.0.1:8080
    names: api-gateway, gateway-helper
  register:
    executetTime: 100
  profiles:
    active: sit